version: "3.8"
services:
  chadburn_service:
    image: premoweb/chadburn:latest
    container_name: chadburn
    depends_on:
      - checkmarks_service
      - firefox_service
    command: daemon
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  checkmarks_service:
    image: checkmarks
    container_name: 'checkmarks'
    labels:
      chadburn.enabled: "true"
      chadburn.job-exec.runscript.schedule: "@every 10m"
      chadburn.job-exec.runscript.command: "./script.sh"
  firefox_service:
    image: 'selenium/standalone-firefox:4.7.1-20221208'
    container_name: 'firefox'
    ports:
      - '4444:4444'
      - '7900:7900'
    build:
      shm_size: '2g'
    shm_size: '2g'
